image: maven:latest

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

cache:
  key: maven-build
  paths:
    - .m2/repository

build:
  stage: build
  script:
    - echo "Misha,Gosha,Nahid,Jamil building the project..."
    - mvn compile

test:
  stage: test
  script:
    - echo "Misha,Gosha,Nahid,Jamil testing the project..."
    - cd src/test/java
    - mvn test
